### ISSUE TITLE
Crashes on the connection to XDJ-RX

### ISSUE THREAD

**Issue by pephumin** [EvanPurkhiser/prolink-tools#1]
Hi,

I really like your idea of displaying track information overlay on OBS. 

But when I tried with my XDJ-RX it crashes on connecting. The XDJ-RX unit freezes, and power cycle is needed.

I wonder if there is anything I can do to help exploring the issue?

**Comment by EvanPurkhiser** [comment]
Hi. Unfortunately this does not work with the XDJ-RX.

See https://github.com/Deep-Symmetry/dysentery/issues/1#issuecomment-348392940
