### ISSUE TITLE
Is it possible to use the overlay without a networked mixer?

### ISSUE THREAD

**Issue by bphillips09** [EvanPurkhiser/prolink-tools#12]
We use a DJM-800 which does not have network capability, but want to use prolink-tools to overlay currently-playing tracks. Could it be modified to assume that the current Master player is the one that is on-air if no networked mixer is available?

**Comment by KayPure** [comment]
it is. the mixer is not important for that use.
i use an 750mk2 and it isnt connected to my network. only the xdj´s are connected.

**Comment by EvanPurkhiser** [comment]
Yes it should _mostly_ just work, though the now playing may not be as accurate.
