### ISSUE TITLE
Link Access Error

### ISSUE THREAD

**Issue by Nevs08** [EvanPurkhiser/prolink-tools#14]
Hi,

after starting the windows server.exe it shows me my 2 XDJ-1000 MK1 (Software Version 1.05) and my DJM 900 NXS. The web overlay says "connected". 

But there will no Tracks Displayed. And after a while it says "E-8309: Link Access Error" on the XDJ 1000.

Can I Debug something to see what happens here or can you help me fix this? 

Best Regards,

**Comment by KayPure** [comment]
The "E-8309: Link Access Error" should not effect your Mix. Since u got this Error, i guess u are Playing in Export-Mode with Rekordbox? Then, u need to run the Server on a different Machine as Rekordbox.

**Comment by Nevs08** [comment]
Jeah i dont think that it effect my mix.

The real problem is that it doesnt show a played track.

I dont use Rekordbox in Exportmode. I just prepared my USB Stick and sticked it into the Players.

**Comment by Nevs08** [comment]
I tried it again with 0.1.0-prerelease.5 and got the same problem. The devices coming up but it doesnt show me any more Information.

So I decided to reinstall the actuall Firmware 1.13 on the XDJ-1000 MK1. This helps me and fixed my problems with that.
