### ISSUE TITLE
Track title from track loaded via Rekordbox link not appearing in UI

### ISSUE THREAD

**Issue by chrisle** [EvanPurkhiser/prolink-tools#15]
Steps:
1. CDJ + mixer is on and connected
2. Rekordbox is open on laptop 1.
3. Load rekordbox track to CDJ, press play on CDJ (loaded via drag and drop in Rekordbox)
4. Start prolink-tools on laptop 2 (connects to network ok, CDJ is detected)
5. prolink reports track is playing but does not display track name

- Restarting prolink-tools doesn't work
- Refresh doesn't work
- Loading another track via drag-drop on Rekordbox doesn't work
- Loading another track via CDJ wheel doesn't work.

Rekordbox 6.0.1 on Mojave (laptop 1)
Prolink-tools running on Catalina (laptop 2)

**Comment by EvanPurkhiser** [comment]
Fixed in https://github.com/EvanPurkhiser/prolink-connect/commit/d4c194d4b1e085ddfd152ec3b194399b6b0c7097
