### ISSUE TITLE
UI appears choppy.

### ISSUE THREAD

**Issue by chrisle** [EvanPurkhiser/prolink-tools#16]
1. Load track on CDJ from USB stick and play
2. Prolink-connect shows title, artist, and artwork
3. Updates to UI appears in bursts.

**Comment by EvanPurkhiser** [comment]
Some additional notes here after talking with Chris:

 - This is not on the frontend, from inspecting a performance recording in the chrome devtools shows there's no frame dropping and lots of room between events.
 - This doesn't happen to me (not my on my machine haha).

I'll instrument some additional performance metrics to see what's going on here.

**Comment by EvanPurkhiser** [comment]
I don't think we're seeing this problem anymore
