### ISSUE TITLE
on startup main window goes white 2 or 3 seconds after opening 

### ISSUE THREAD

**Issue by mattpstv** [EvanPurkhiser/prolink-tools#18]
I've installed "prolink-tools-0.1.0-prerelease.1-mac.dmg" release on two different Macs, both running running macOS 10.15.5 (a 2019 MacMini and a MacBook Pro Retina Early 2015), and I keep on running into the same issue: after starting up the ProLink window goes all white after about 3 or 4 seconds. I can see which players are online most of the time by the graphics before the whit window obscures all. I've tested with and without players being connected to Pro Link network. I've tested both computers via wifi and ethernet connection to network. Rekordbox (Export) Link is off (or RB is not running). Let me know if I can help via logs or whatever. Here's an exciting two part screen shot of what is happening. I can't post a video here, but i can link you to a google drive share if you want. 

<img width="493" alt="Screen Shot 2020-06-05 at 4 58 39 AM" src="https://user-images.githubusercontent.com/44700535/83863772-6b89b880-a6e9-11ea-9aa6-bdb3b736b5fa.png">
<img width="580" alt="Screen Shot 2020-06-05 at 4 59 13 AM" src="https://user-images.githubusercontent.com/44700535/83863806-78a6a780-a6e9-11ea-80bc-2bba4ec09e80.png">

**Comment by EvanPurkhiser** [comment]
Hi Matt, thanks for sharing :)

I think this should be fixed in the latest prerelease.

I'll be making Alpha builds available soon which will include more error reporting, in this particular case I didn't get any error reports since I hadn't integrated tooling for that yet.

**Comment by mattpstv** [comment]
Hey Evan, I'm psyched to see you taking this project to the proverbial next level. I've used the older version quite a bit, but I'm also happy to see what I am seeing right now with the latest build: I'm running it from my macbook which is on the network via wifi, where as all Pro Link players are on same network but via ethernet cable/hub (I often had an issue with this wifi/cable setup before). If I get a chance this morning I'll try my hardest to break it by complicating my setup and adding a variety of Pioneer DJ devices which semi-interact with Pro Link, run RB Export LINK mode (I'm on RB 5.6 still, though I can try RB6 Export) on a second machine and/or run Beat Link Trigger on a pi, etc etc. Here's what I'm seeing and I like it (ps. Player 1 is a DJS-1000, so obviously there's no track info to populate, put I like that it at least shows up as a connected device with most of the info the xdj-1000mk2s show). Your work is appreciated.  m+
<img width="743" alt="PROLINKTOOLS-screenshot01-working-JUNE19-2020(w00t)" src="https://user-images.githubusercontent.com/44700535/85128302-99e1ba80-b1f6-11ea-808c-109973f1bc9c.png">
