### ISSUE TITLE
global.process is undefined

### ISSUE THREAD

**Issue by Nevs08** [EvanPurkhiser/prolink-tools#20]
After fixing my first Problem i wanted to test the Overlay at v0.1.0-prerelease.5

But at the Browser it doesnt show me anything and in the Firefox Console i found this:

![grafik](https://user-images.githubusercontent.com/9518503/87304720-897ee000-c515-11ea-9be8-7d788adbe179.png)

**Comment by Nevs08** [comment]
On Chrome i got this error: 

![grafik](https://user-images.githubusercontent.com/9518503/87305182-5ab53980-c516-11ea-90af-9a4b23a26c02.png)

**Comment by EvanPurkhiser** [comment]
This was downloaded right from the release right?

**Comment by Nevs08** [comment]
Yes, i also tried the new prerelease.6 yesterday but got the exact same error.

**Comment by KayPure** [comment]
same here. was the first time i tried the release. was using prolink overlay in the past.

**Comment by KayPure** [comment]
> **Edit: I tried it in a VM with Debian 10 and it worked at the Debian Firefox the Windows Firefox and at OBS. So it looks like theres a problem at the Windows Version or on my 2 Windows Computer**

i guess its a problem with windows. tested it the same way yesterday. linux mint in a vm. 
chrome (windows) displays the overlay
firefox (mint) displays the overlay
obs (windows) displays the overlay as well

after this testing, i startet the old "prolink-overlay" server on my windows machine. if i run the server by the windows 10 shell, the overlay is blank. even if i was able to configure it, it shows nothing. if i start the server by the cmd prompt, the overlay works just fine. perhaps this is important to locate the issue? 

greetings from germany

**Comment by densma1** [comment]
@KayPure 
can you provide instructions on how to run on windows cmd prompt for overlay to work?
I understand there's a problem with windows but you seem to have found a workaround?
Thanks

**Comment by KayPure** [comment]
> @KayPure
> can you provide instructions on how to run on windows cmd prompt for overlay to work?
> I understand there's a problem with windows but you seem to have found a workaround?
> Thanks

Oh sorry for the confusion. Its an old version of this repo, not the same. I guess you can't download it anymore. In this old version, the overlay works fine if i start the script via command prompt. If i start it via shell, It shows nothing.

**Comment by densma1** [comment]
@KayPure 
i think previous builds still available. Do you know which version was that?

**Comment by KayPure** [comment]
> @KayPure
> i think previous builds still available. Do you know which version was that?

Mit exactly. It hast no gui and we has to run it via cmd. There was an webinterface for the settings.

**Comment by KayPure** [comment]
@densma1 
here you go [https://www.dropbox.com/s/3t2xclimq8d8pzv/Prolink-Overlay.rar?dl=0](url)

i hope its okay to link an older version/repo of this tool ?!

**Comment by densma1** [comment]
@KayPure 
Thanks
@EvanPurkhiser I hope Overlay fix is coming with the newer version. its pretty cool tools. thxs

**Comment by densma1** [comment]
@KayPure
Just trying to test it now. overlay works well on http but how do i get my content to display instead of random examples.
how can i replace these https://ibb.co/Lk0Cvxb with my actual metadata from player?

**Comment by KayPure** [comment]
> @KayPure
> Just trying to test it now. overlay works well on http but how do i get my content to display instead of random examples.
> how can i replace these https://ibb.co/Lk0Cvxb with my actual metadata from player?

I guess this is the config http, right? Copy the url above after configuration an open it in a new browser/obs

**Comment by densma1** [comment]
@KayPure Yes. just cant get my content. seem like the html need some modification to use pro-link data instead of sample data.

**Comment by KayPure** [comment]
> @KayPure Yes. just cant get my content. seem like the html need some modification to use pro-link data instead of sample data.

That's strange. If you start the script, is there any pioneer gear found and displayed in the command prompt? For me, i start the script and configure the output via the url. Then, I copy the url from the config site and paste it where it should go. That's it. One thing I notice a few times: if nothing is displayed, I restart the script while the gear is running. 

Sounds like there is any issue with your setup. I run the script on a dedicated machine? It won't run on the same machine as rekordbox. In case u use rekordbox in export mode.

**Comment by densma1** [comment]
@KayPure  Yes. dedicated machine. right now only have one device on the network.
command prompt shows started and my cdj is found
https://ibb.co/L03G21Q
here's the http page
https://ibb.co/W3Kqqfc
configure output? what else i need to configure on this screen before i copy?
maybe i'm missing something. 
Thanks

**Comment by KayPure** [comment]
thats how i do it and it worked after i restart the gear and the script 2 times. sometimes i cant play or even link if i start the script first. 
1: start the gear
2: start rekordbox on another pc and link http://prntscr.com/ulyiez
3: start the script http://prntscr.com/ulyiwn - rekordbox shows another device http://prntscr.com/ulyj4z
4: open the config page and edit settings. then, copy the browser url http://prntscr.com/ulyjr9
5: paste it in obs and play my tracks. done - http://prntscr.com/ulyn8s - even on the config page the tracks are shown - http://prntscr.com/ulynqp

thats all i can say about it. did u tested it with older cdj´s? perhaps there are some issues with the new 3000!?

**Comment by densma1** [comment]
@KayPure 
I will retest later. why is rekordbox needed?
i didnt have rekordbox running. Are you sure rekordbox is needed?

**Comment by densma1** [comment]
i'm using usb not export mode. I dont think it has anything to do cdj-3000. That's only device i have now.
I will try export mode too

**Comment by KayPure** [comment]
> @KayPure
> I will retest later. why is rekordbox needed?
> i didnt have rekordbox running. Are you sure rekordbox is needed?

Its not needed. But if you use it, u can't run it on the same machine as the script. Because rekordbox uses unique sockets which can only read from one instance on one machine at the same time. 

What about your firewall? Try to disable it to test. If its working, delete all entrys related to the script from you're firewall and reopen it.

**Comment by densma1** [comment]
didnt work but will test shortly on another laptop. maybe its cdj-3000. I returned XZ for 3000. I dont any other older  deck. I have DJS-1000 but really no metadata from it

**Comment by densma1** [comment]
@KayPure same issue. what exactly do you have to configure on this screen https://ibb.co/W3Kqqfc

**Comment by KayPure** [comment]
> @KayPure same issue. what exactly do you have to configure on this screen https://ibb.co/W3Kqqfc

depends on you. i use only the comment and label metadataitems. everything else is deleted. thats all

**Comment by EvanPurkhiser** [comment]
This is now fixed in the latest releases.

This was due to how I was bundling my error monitoring telemetry.

**Comment by densma1** [comment]
Thanks.. works perfect with cdj-3000
