### ISSUE TITLE
Cannot read property 'cwd' of undefined

### ISSUE THREAD

**Issue by cottinghamd** [EvanPurkhiser/prolink-tools#25]
There is a bug in the latest release where the OBS overlay will be blank on Windows machines, regardless of the browser used. CDJ and track information show fine in the main electron app, however the linked browser URL for the OBS overlay does not display data.

Browser dev tools reveals an Uncaught TypeError. Attached is a photo of my screen (yes laugh it up, it's from my other pc :P)

![115876109_583423845660902_3031650983317102523_n](https://user-images.githubusercontent.com/18164412/90008863-5bd9b200-dce0-11ea-9d9f-96e26f90f2e4.jpg)

**Comment by cottinghamd** [comment]
This is a duplicate of issue #20

**Comment by KayPure** [comment]
yeah, ive run into the same issue. its windows i guess. tested it on linux and it worked like it should. we have to wait until this is fixed by evan. my workaround: ive started a vm with a small linux build (mint) and start the overlay from this vm.
