### ISSUE TITLE
change the way, the overlay is updating the new track?

### ISSUE THREAD

**Issue by KayPure** [EvanPurkhiser/prolink-tools#26]
just a question for me: since i use an djm750mk2 which one has no lan port, the track will update everytime i hit the play button on the decks. i use the beat link trigger tool too and make a txt file of my current playing tracks. this txt file is updated, when i hit the cue button on the last played deck.

deck a > play > txt file update with track a
deck b > play > fade to deck a
deck a ends > cue > txt file update with track b metadata

perhaps this is possible with the pro link overlay? if i change something in the code? whould love to use this overlay, but its annoying to see the overlay updating everytime i hit play. even if i just search a track and quick search through it, the overlay will update.

**Comment by EvanPurkhiser** [comment]
In the future I think what I would like to do in the case where there's no On-Air indicator is to allow a hotkey to be configured to mark a track as live.

I like this solution as well. I just need to add a configuration so that the user can indicate they don't have on-air status.

**Comment by EvanPurkhiser** [comment]
This will now automatically work. 

If you don't have a mixer on the network it will default to only reporting now-playing tracks when the 2nd deck has been cued / ends / paused / etc

**Comment by KayPure** [comment]
awesome evan, thanks!!
