### ISSUE TITLE
rekordbox, pro link see DJM900NXS2 and CDJ2000's, but prolink tools sees nothing, says "offline"

### ISSUE THREAD

**Issue by misternathaniel** [EvanPurkhiser/prolink-tools#28]
Isn't seeing my gear.

devtools error says:

DevTools failed to load SourceMap: Could not load content for file:///Applications/Prolink%20Tools.app/Contents/Resources/app.asar/dist/app.js.map: 

please advise!

**Comment by Nevs08** [comment]
Do you opened prolink tools on the same machine as rekordbox?

**Comment by misternathaniel** [comment]
Oh, yes.  Is that no good?

**Comment by Nevs08** [comment]
Nope. You have to open rekordbox and prolink on different machines if you want to use both at the same time.

**Comment by EvanPurkhiser** [comment]
I've added a notice to the app now to give some hints (including rekordbox requirements) when it fails to connect.
