### ISSUE TITLE
Fixed HTML Classes 

### ISSUE THREAD

**Issue by MonioDesign** [EvanPurkhiser/prolink-tools#30]
I've been playing around with the overlays which are working great but trying to style them is pretty tricky.

I'm using CSS to tweak the look of the overlays such as changing the font, hiding the artwork and other bits however with the way it's constructed (I'm guessing react?) all the elements have generated CSS classes e.g "css-uj3pkk". It would be great if there could be some fixed classes like 'current-track', 'previous-tracks', 'title', 'artist', etc. It would make styling them a load easier.

Would also be awesome to override the animations too to create some other custom ones :)

Here's how I've got it looking so far...

![Screenshot 2020-10-19 at 14 14 45](https://user-images.githubusercontent.com/6203649/96456582-91d26f80-1216-11eb-8f87-0fa36d04da7e.png)

With this CSS...

```css
body{
  background-color: #000;
}
body > div > div:nth-child(1){
  gap: 0;
}
body > div > div:nth-child(1) > div > div:first-child {
  display: none;
}
body > div > div:nth-child(1) > div > div:last-child > div:last-child{
  display: none;
}
body > div > div:nth-child(1) > div > div:last-child > div{
padding: 0px;
margin: 0px;
font-family: arial;
font-weight: bold;
text-transform: uppercase;
letter-spacing: -0.05rem;
font-size: 32px;
line-height: 32px;
background:none;
}
body > div > div:nth-child(1) > div > div:last-child > div:nth-child(2){
  opacity: 0.8;
}
body > div > div:nth-child(2) > div > div:first-child{
  display:none;
}
body > div > div:nth-child(2) > div > div:last-child > div{
  padding: 0px;
  margin: 0px;
  font-family: arial;
  font-weight: bold;
  text-transform: uppercase;
  letter-spacing: -0.05rem;
  font-size: 16px;
  line-height: 16px;
  background:none;
}
body > div > div:nth-child(2) > div > div:last-child > div:nth-child(2){
  opacity: 0.5;
}
body > div > div:nth-child(2) > div > div:last-child > div:last-child{
  font-size: 11px;
  line-height: 11px;
  opacity: 0.3;
}```

**Comment by EvanPurkhiser** [comment]
Oh man, yeah that's some wild CSS :)

You're right, class names are all autogenerated by emotion.

You're also correct that this is all react.

My plan originally was to have various overlay 'styles' maybe even overlay themes, that you can configure in the overlay settings. I'm not sure where I've landed on customization yet. But I think i can definitely add some fixed class names.

I'll add some :)

**Comment by GameGrime** [comment]
I was actually about to start doing some CSS editing for this, and came to the same conclusion as OP. I would love to get an update. The default looks good for now however.

**Comment by EvanPurkhiser** [comment]
These are now available as of https://github.com/EvanPurkhiser/prolink-tools/commit/521ae32e7d00586a7a4fda32eec2bd988060dcc0. The [development build](https://github.com/EvanPurkhiser/prolink-tools/releases/tag/master-build) is building as we speak :)

**Comment by MonioDesign** [comment]
> Oh man, yeah that's some wild CSS :)
> 
> You're right, class names are all autogenerated by emotion.
> 
> You're also correct that this is all react.
> 
> My plan originally was to have various overlay 'styles' maybe even overlay themes, that you can configure in the overlay settings. I'm not sure where I've landed on customization yet. But I think i can definitely add some fixed class names.
> 
> I'll add some :)

Awesome thanks for that!

I've been using CSS styles and animation to customise the overlay, giving it a test on a stream at the weekend and this'll definitely help going forward!

Maybe have some way for people to expand it themselves and have overlays we can share? I know that's a fairly big thing to build in but then anyone handy with CSS/javascript could come up with some different overlays and share with the community.

**Comment by EvanPurkhiser** [comment]
I've been thinking about a way for people to be able to plugin overlays. Don't have any concrete ideas yet.

But the possibilities are real! You can use pretty much everything the CDJs expose as an overlay.

For example, something fun I wanted to build was a 'cue smash counter', which would be a fun little stat overlay that tells you how many times you've pressed the cue button during your set, and maybe other silly stats like 'fastest cue press' and (most cue presses within 5 seconds) etc etc hahaha

**Comment by MonioDesign** [comment]
That does sound cool, would be great to see what people did with it! certainly make live streams fun. Maybe also use it to drive visualisations even too, lots of possibilities.

I've also got the DJS-1000 which I haven't plugged into this setup yet (it does have pro link enabled) so be interesting to see what that kicks out.

**Comment by GameGrime** [comment]
@EvanPurkhiser I know I'll be watching this program closely, seems to be in good hands with those ideas :)

**Comment by MonioDesign** [comment]
I did a livestream at the weekend and it worked great, made a few little tweaks to my customisation - here's how I got it looking (you'll see the text flashes up large at first, then shrinks down). It's a god damn live saver for all those that usually ask me for a track listing lol

https://youtu.be/PfSeQvJCRDY?t=1139

**Comment by EvanPurkhiser** [comment]
@MonioDesign That looks fantastic :) Definitely thinking it would be cool to have a way to write CSS right in the app.

Really awesome man, subbed to your channel to!

**Comment by EvanPurkhiser** [comment]
Theme's are coming ;-)

![image](https://user-images.githubusercontent.com/1421724/99672316-15ef6100-2a28-11eb-9add-eba0939f8549.png)

**Comment by MonioDesign** [comment]
That's awesome, great to hear!

Hopefully a nice way to create your own too? ;)
