### ISSUE TITLE
No Track Info - Version .11

### ISSUE THREAD

**Issue by matt-whitlock** [EvanPurkhiser/prolink-tools#31]
Hi, version .11 fixed the blank white screen but still no track info now when playing. Any ideas? I'm on Mac 10.15.7

<img width="693" alt="Screen Shot 2020-10-19 at 10 01 40 AM" src="https://user-images.githubusercontent.com/73094990/96487938-25de1000-11f2-11eb-895a-c13046e11fc9.png">

**Comment by EvanPurkhiser** [comment]
What was the problem?

**Comment by EvanPurkhiser** [comment]
Oh that's interesting, even if you do something like: ?

```
internet -> switch -----|
            |    |      |
            V    V      V
           CDJs  mixer  iMac
```

**Comment by matt-whitlock** [comment]
Just tried that, internet works fine, but "Waiting For Prolink Devices" is shown and will not detect CDJs or mixer. CDJ link works fine.

**Comment by EvanPurkhiser** [comment]
Does rekordbox work on the PC in that configuration?

**Comment by EvanPurkhiser** [comment]
Something else important to note is you have to restart your CDJs for them to correctly configure their network when connected to a router. If they can't get a dhcp lease they will just default toconfiguring themselves on their own subnet to talk to each other, and won't appear on the network.

By restart I mean boot them after being connected to the switch.
