### ISSUE TITLE
Not working with CDJ-3000 and 3.0 Firmware

### ISSUE THREAD

**Issue by nzoschke** [evanpurkhiser/prolink-tools#326]
I just upgraded my CDJs to the new [3.0 firmware](https://www.pioneerdj.com/en/support/software/player/cdj-3000/). 

Prolink tools shows connected, and shows the IPs of the 2 CDJs but doesn't get any events or track listing.

This was all working at one point so I suspect the 3.0 firmware 😢

<img width="1032" alt="Screenshot 2023-07-18 at 6 55 05 PM" src="https://github.com/evanpurkhiser/prolink-tools/assets/147410/5eeadbff-5d39-49b4-87df-aa49deef183a">

**Comment by evanpurkhiser** [comment]
Oh no!

This will probably take me some time to get around to unfortunately :( I am planning to pickup some 3000s some time in the future, but I'm still waiting for the global shortage to calm down.

**Comment by nzoschke** [comment]
It's working now!! CDJ-3000s on the latest firmware.

I didn't do another firmware update or anything, so maybe something rebooting, new network adapter, etc.

Sorry for the false report and thank you for the awesome app.
