### ISSUE TITLE
Not an issue - Just a big thanks

### ISSUE THREAD

**Issue by bendursley** [EvanPurkhiser/prolink-tools#33]
Have been keeping an eye on this project since the start of the year, gave it a try then but couldn't get the overlay to work at that point (should of reported it at the time).  

Given it another whirl with the most recent alpha build.  Really like the electron app you've built and the overlay works now.  Really impressed with all of this, well done!

**Comment by wompapmow** [comment]
Is there anything you needed to do to get the overlay working? I just submitted #32 because I can't get the data to populate

**Comment by bendursley** [comment]
@wompapmow no.  My Nexus 2s and DJM 900 NXS2 are all linked and I've got On Air mode on for them.  Then just created an overlay.  Everything is lan connected (including a rekordbox PC and my streaming PC which is running the app)
