### ISSUE TITLE
Overlay jumps around

### ISSUE THREAD

**Issue by bendursley** [EvanPurkhiser/prolink-tools#34]
One thing I've noticed from playing around with this this evening is that the Overlay tends to jump around in OBS within it's browser window based on the lengths of track names.  Is there a recommended size for the browser window to stop this?
I've got everything right aligned but notice it when I briefly tried left align to.

**Comment by bendursley** [comment]
Going to close this.  Turns out I left the default custom CSS in the browser source and it was forcing the track info to the centre.  Removing it solves this.

**Comment by wompapmow** [comment]
I ran into the same issue and had the same fix @bendursley! I figured it out on my own but thank you for sharing your solution, hopefully this helps someone else

**Comment by EvanPurkhiser** [comment]
I'll see if I can add something to detect the default OBS browser CSS and add a warning for it.

The margin stuff looks new.
