### ISSUE TITLE
unable to find rekordbox v6.0.3 with DDJ 800 connected

### ISSUE THREAD

**Issue by Moliwell** [EvanPurkhiser/prolink-tools#36]
Not sure if this is an issue or if you cannot use the app when playing with a DDJ Controller via Rekordbox. 

when both are open pro tools just keeps connecting and says Waiting for Prolink Services.

**Comment by EvanPurkhiser** [comment]
Unfortunately all DDJ controllers are not supported, since they do not support the pro dj link feature.

I need to note this in the readme, but I believe the supported list would be, any CDJ that has a "Link" or "rekordbox" button, and connects via ethernet.
