### ISSUE TITLE
Latest development build Beta2 can not change menu

### ISSUE THREAD

**Issue by GameGrime** [EvanPurkhiser/prolink-tools#37]
Experienced an odd issue on the latest dev build. Where I could not click on any other menu. Reloading the UI via the View menu fixed the issue.

**Comment by EvanPurkhiser** [comment]
Fixed in https://github.com/EvanPurkhiser/prolink-tools/commit/67c9f4d5d53b136f8ffba5d36fd17d0c626067e1
