### ISSUE TITLE
http proxy error

### ISSUE THREAD

**Issue by KayPure** [EvanPurkhiser/prolink-tools#4]
i get this debug error if i connect to the webserver. any ideas what ive done wrong?

http: proxy error: dial tcp [::1]:9000: connectex:

**Comment by EvanPurkhiser** [comment]
If the static assets aren't compiled into the built binary then it will try and talk to the webpack server. You'll have to make sure you have `rice` installed and that the static assets were added [in this step of the makefile](https://github.com/EvanPurkhiser/prolink-overlay/blob/master/Makefile#L20).
