### ISSUE TITLE
Request: overlay text in uppercase only

### ISSUE THREAD

**Issue by normannetro** [EvanPurkhiser/prolink-tools#41]
Hi 
First of all a big thanks, this app is exactly what I was looking for.
To my question, is it possible to show the complete overlay text from the theme "a State of overlay" in capital letters?

**Comment by EvanPurkhiser** [comment]
Yes! you could use some custom css for this.

If you're using OBS or StreamLabs you can add this code to the `Custom CSS` field of the browser source.

```css
.track-current {
	text-transform: uppercase;
}
```

Like such:

![image](https://user-images.githubusercontent.com/1421724/104979256-a90d2e80-59b8-11eb-9df7-f5fd3f5c9fde.png)

**Comment by normannetro** [comment]
Thanks man, great app and good work. You made my day :)
