### ISSUE TITLE
Labels not showing with rekordbox

### ISSUE THREAD

**Issue by andyweiss7** [EvanPurkhiser/prolink-tools#42]
Labels name not showing when rekordbox is connected with RJ45 but it’s work with the USB stick on the CDJ.

maybe a tag problem ? « publisher » tag

**Comment by EvanPurkhiser** [comment]
Try the latest development build here https://github.com/EvanPurkhiser/prolink-tools/releases/tag/master-build

I believe this issue is fixed.

**Comment by andyweiss7** [comment]
Thanks for your reply, but same problem with the last version, comments, album, key & tempo are working and i'm sure 100% my label tag is correct on my file.

Tested with .mp3 & .aiff format

**Comment by EvanPurkhiser** [comment]
Oh I see what you're saying.

you might need to add the columns to this setting page 
![image](https://user-images.githubusercontent.com/1421724/106956152-09a3a780-66eb-11eb-82f8-ad21f1560415.png)

**Comment by andyweiss7** [comment]
Nice ! fixed, thanks a lot 💪

**Comment by EvanPurkhiser** [comment]
Awesome! Feel free to hop in the discord if you have any other questions :)
