### ISSUE TITLE
Some "issues"

### ISSUE THREAD

**Issue by KayPure** [EvanPurkhiser/prolink-tools#5]
hey evan,

first of all: this is an amazing tool. love it!

I run it on a windows 10 machine and run into 2 little "i ssues". 

1: on my xdj 1000mk2 Player, ive got the error"E-8309 Link Access Error"
the player will play without any problems and the Error comes and goes every xy seconds. thats not a big deal, since the music wont stop and everything runs just fine.

2: If I loaded a new track, it will not always be displayed the same way. some times it displays the track right after loading. some times it displays after xy seconds without playing, only cue´ed. some times it displays the track after 16bars, which is right i guess. 

one question: is there a way to delete the cover section from the overlay?

greetings from germany!

*edit*
it seems that rekordbox is the issue. if i play from usb sticks, everything works as expected. most of the time i play from rekordbox with linked players.

**Comment by markusglow** [comment]
Hi Evan
here's the same problem.
every 15 seconds, players display the link. Error.
the players cdj2000nxs working fine.
Even if I play with linked USB stuck, error showing up.
newest firmware on the player and also rekordbox is on the newest 5.x version

**Comment by cottinghamd** [comment]
Hey Guys, I think there is a limitation where it does not work with rekordbox at all, this is because Rekordbox locks exclusive socket access to the CDJ's and the overlay can no longer read the players.

You must have rekordbox closed before launching the overlay

**Comment by markusglow** [comment]
Nope.. It also happen if rekordbox is closed and only play with linked USB stick.

**Comment by jstrollis** [comment]
To add some information here, I was just testing this out on a 2015 macbook pro that I have upgraded to catalina and ran into the exact same problem.

setup overview:
2015 macbook pro / os x catalina (upgrade - not clean install)
apple branded thunderbolt to ethernet adapter
trendnet teg-s82g 8 port gigabit ethernet switch
2x xdj-1000mk2 (latest firmware installed today)
128G and 256G samsung USB drive

I have a feeling there is an issue with using such large drives, as it took nearly 6 minutes to start loading track info data to be displayed, but then it worked for the playlists I was in.  Once I switched playlists it took another 5-6 minutes to load data. 

Every 1-3 minutes I get E-8309 Link Access Error, although the tracks continue playing and the error goes away within just a few seconds.



I'm going to test smaller USB drives, a different switch, new cables, and a windows 10 laptop to see if the issue continues.  I can also try direct connecting a player to the laptop without a switch and see how that goes.  I had read somewhere (although can't find the article anymore) that pioneer can be finicky with switches and prolink, however I've had this switch for ~2 years with no problems just direct connecting players together.  I'll report back later.

**Comment by pixelrock** [comment]
Hey guys, also having the same issue: tried on Windows & Mac, with static IPs and dhcp - I can see the cdjs (2x CDJ2000)  coming on but don't get any events on play/stop etc. beatlinktrigger seems to work fine though. Also getting the E-8309 Link Access Error, no Rekordbox on the network. looking forward to solve this, awesome work btw!
best, matthias

**Comment by markusglow** [comment]
The link access error is normal, cause this open source project doesn't have a legal license from Pioneer 😉

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by EvanPurkhiser** [comment]
I believe all of these issues should be fixed now :)
